### ISSUE TITLE
traits, structs, and keywords relating to them are all the same color

### ISSUE THREAD

**Issue by crumblingstatue** [Nercury/atom-rusty-dark-syntax#2]
Traits and structs are quite different things. They both get their own color in rustdoc output, so it's confusing that they have the same color here.

Keywords should definitely be a different color than non-keyword identifiers.
![](http://i.imgur.com/uC8GaCA.png)

**Comment by Nercury** [comment]
Yes, I have explained in #1 that `rust-language` does not give us enough info here to do that (last checked a month ago).

**Comment by Nercury** [comment]
But thanks for report, I will probably look into this again!
